# Generated by Django 4.2.11 on 2024-04-24 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_historicalweather'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalWeather',
        ),
    ]
