# Generated by Django 4.2.11 on 2024-04-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_historicalweather'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
